#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: Brendan Good
#+DATE: 2018-04-11 Wed 19:44
#+TITLE: Understanding Natural Transformations
#+DESCRIPTION: Natural transformations are critical in understanding category theory, here I'll explain them as I understand them
#+TAGS: category theory,natural transformations
#+CATEGORIES: math,category theory
#+LATEX_HEADER: \usepackage{amsfonts}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amscd}

Natural transformations are the gatekeeper to the rest of category theory. Once you understand them, adjoint functors and even the (in)famous monads unveil themselves. In fact,
the "correct" notion of two categories being equivalent (unsurprisingly called an equivalence of categories) relies on natural transformations.

Despite this notion being critical, I've always found the typical explanations unenlightening such as "coordinate free transformations" (what does that even mean) and "homomorphism of functors".
As is often the case for me, the best approach for me was stare at the diagram and figure out what it means.

In this post, I'll talk about my intuition for natural transformations and, roughly, how I came to them. Although the understanding I ultimately came to is pretty much identical
to the "homomorphism of functors" viewpoint, I'll unwind the analogy a bit more.

Now, what is a homomorphism, really? A map which preserves the structure of its argument. I.e., a group homomorphism is a map which sends groups to groups,
a "category homomorphism" (functor) sends categories to categories, etc. This doesn't get us much further without first, ironically, taking a step back; what is the "structure of a functor"?
It's a strange question with a straightforward answer, you apply it. You give me an element of category $C$, I'll give you an element of category $D$. Similarly, you give me a morphism in $C$,
I'll give you a morphism in $D$.

Before we go diving into the intuition, here's the definition of a natural transformation (which is a 90 degree rotation from the one [[https://en.wikipedia.org/wiki/Natural_transformation#Definition][listed on Wikipedia]]).

A natural transformation is a morphism $\eta: D\to D$ such that for each $X,Y\in ob(C)$, we have that the following diagram commutes.
\[\begin{CD}
F(X) @>\eta_X>> G(X) \\
@VF(f)VV        @VVG(f)V \\
F(Y) @>\eta_Y>> G(Y)
\end{CD} \]
Where $f\in mor(X,Y)$

So how does this show those properties I said earlier? If I have a functor $F$, I can apply it to an element $X$ and get an element of $D$, the top arrow says that you can take that
element $F(X)$ and get another element $G(X)$ of $D$ the bottom arrow is the same story. Therefore, we have the object part down. If I have some object from $D$ via $F$, I can get some
objects from $D$ via $G$ as well.

Now what about morphisms being preserved? Note that if we stop here, with only mappings of objects, we have the following diagram:

\[\begin{CD}
F(X) @>\eta_X>> G(X) \\
@VF(f)VV        @. \\
F(Y) @>\eta_Y>> G(Y)
\end{CD} \]

This could put is in an uncomfortable situation where we map to objects $G(X)$ and $G(Y)$ that have no morphisms between them. The arrow on the right now amounts to us needing to have a morphism in
$D$ between the derived objects $G(X)$ and $G(Y)$.

* An odd example that made it click for me
At a Haskell meetup, the organizer ([[https://gbaz.github.io/][Gershom Bazerman]]) said "When people ask me for references on category theory, I say 'the second one you end up reading'",
and I suspect that there may be an element of that here. Nonetheless, even though it's not a natural transformation, it helped me further understand "structure preserving functions".


** Chain complexes

A chain complex $C_\bullet$ (or just $C$) is a collection of $R-\text{modules}$ $C_i$ along with module homomorphisms $d_i: C_i\to C_{i-1}$ such that $d_{i-1}\circ d_{i} = 0$

\[\begin{CD}
... @>d_{n+2}>> C_{n+1} @>d_{n+1}>> C_n @>d_n>> C_{n-1} @>d_{n-1}>> ...\\
\end{CD}\]

In particular, note that the kernel of $d_{i-1}$ is a submodule of the image of $d_i$ (since $d_{i-1}\circ d_{i} = 0$), one of the things that we're interested in when we study chain complexes
 is the kernel of $d_{i-1}$ (called cycles) and the image of $d_i$ (called boundaries) in particular how much bigger the kernel is than the image; in other words, we care to measure the degree
to which this diagram is not exact.

From now on, I'll simply refer to the morphisms $d_i$ as simply $d$.
** Morphisms of chain complexes

A morphism of chain complexes from $C_\bullet \to D_\bullet$ is a collection of morphisms $u_i: C_i\to D_i$ such that the following diagram commutes.

\[\begin{CD}
... @>d>> C_{n+1} @>d>> C_n @>d>> C_{n-1} @>d>> ...\\
@.        @Vu_{n+1}VV   @Vu_nVV     @Vu_{n-1}VV\\
... @>d>> D_{n+1} @>d>> D_n @>d>> D_{n-1} @>d>> ...
\end{CD}\]

It can be proven via [[https://en.wikipedia.org/wiki/Five_lemma#Proof][diagram chasing]] that $u$ sends cycles to cycles and boundaries to boundaries, which is to say, chain complex morphisms preserve precisely the structure that we're interested in.

So, even though natural transformations may be intimidating at first, it is simply a way to say that two functors have the same structure; I hope this explanation has been helpful!
