#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: Brendan Good
#+DATE: 2018-04-11 Wed 19:44
#+TITLE: Understanding Natural Transformations
#+DESCRIPTION: Natural transformations are critical in understanding category theory, here I'll explain them as I understand them
#+TAGS: category theory,natural transformations
#+CATEGORIES: math,category theory
#+LATEX_HEADER: \usepackage{amsfonts}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amscd}

Natural transformations are the gatekeeper to the rest of category theory; once you understand them, adjoint functors and even the (in)famous monads unveil themselves. In fact,
the "correct" notion of two categories being equivalent (unsurprisingly called an equivalence of categories) relies on natural transformations.

Despite this notion being critical, I've always found the typical explanations unenlightening such as "coordinate free transformations" (what does that even mean) and "homomorphism of functors".
As is often the case for me, the best approach for me was stare at the diagram and figure out what it means. Although the understanding I ultimately came to pretty much identical
to the "homomorphism of functors" viewpoint, I'll unwind the analogy a bit more.

Now, what is a homomorphism, really? A map which preserves the structure of its argument. I.e., a group homomorphism is a map which sends groups to groups,
a "category homomorphism" (functor) sends categories to categories, etc. This doesn't get us much further without first, ironically, taking a step back; what is the "structure of a functor"?
It's a strange question with a straightforward answer, you apply it. You give me an element of category $C$, I'll give you an element of category $D$ (and similarly with morphisms).

This notian is summed up neatly in one diagram (which is a 90 degree rotation from the one [[https://en.wikipedia.org/wiki/Natural_transformation#Definition][listed on Wikipedia]]).

\[\begin{CD}
F(X) @>\eta_X>> G(X) \\
@VF(f)VV        @VVG(f)V \\
F(Y) @>\eta_Y>> G(Y)
\end{CD} \]

If I have two functors, $F$ and $G$,

* an odd example that made it click for me
At a Haskell meetup, [[https://gbaz.github.io/][Gershom Bazerman]] said "When people ask me for references on category theory, I say 'the second one you end up reading'", and I suspect that there may be an element of that here.
Nonetheless, it's an example that I haven't quite seen elsewhere that may be enlightening.

**
